.\" Manpage for dice-roller
.TH man 1 "17 February 2018" "1.6" "dice-roller man page"
.SH NAME
dice-roller \- rolls a dice using standard dice notation
.SH SYNOPSIS
dice-roller <dice code>
.SH DESCRIPTION
dice-roller is a python application for rolling dice using standard dice notation. Used in games such as dungeons and dragons.
.SH OPTIONS
dice-roller does not take any options just dice codes

